### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [PaulRegular/SimSurvey#10]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by PaulRegular** [comment]
Thanks for flagging this as I missed the news that the raster package is being retired. **SimSurvey** now uses the **sf/stars** packages in lieu of the **sp/raster** packages. For now, I have retained **rgdal** as an Import as it is required for the **INLA** package.

**Comment by rsbivand** [comment]
The **raster** package is *not* being retired, and now uses **terra** for everything **raster** previously used **rgdal** and **rgeos** for. **INLA ** only suggests **rgdal** and **rgeos**, which means that it promises to run when they are absent. You should remove **rgdal** from `Suggests:` by say June 2023` and check that is is available before any use. Best to remove it completely.

**Comment by PaulRegular** [comment]
Ok, thanks for clarifying! I have now removed **rgdal** from `Suggests:`
